### ISSUE TITLE
Reading basics from a file instead of single line. Related to #2

### ISSUE THREAD

**Issue by flrnd** [Anarcroth/mish-mash#5]
Hi! First of all, great job! I really like this project!

Regarding #2. Any reason why basics is a single line instead of a .txt or .html? I could work on that feature if it's okey.

**Comment by Anarcroth** [comment]
Hello and thanks!
Honestly, I just did it cuz it was quick and it worked. If you intend to put it in a separate file, then some of the server code has to be changed to parse that :)

**Comment by flrnd** [comment]
It's not a big deal, but it's a bit easier to edit in a separate file. Anyway, PR incoming!
